# -*- coding: utf-8 -*-
"""apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12maCmyMMOW5Tgg00iN_qSZiBIDzD65Dv
"""

import requests
import re


def recommend_books(query, start_index=0, max_results=5):
    api_key = "AIzaSyBTUN2rpDiGhgvPHSECz0uIAEFTbn_I3I8"  
    url = f"https://www.googleapis.com/books/v1/volumes?q={query}&startIndex={start_index}&maxResults={max_results}&key={api_key}"

    response = requests.get(url)
    books = response.json()

    recommendations = []

    if 'items' in books:
        for item in books['items']:  
            book = {
                "title": item['volumeInfo'].get('title', 'No title available'),
                "authors": item['volumeInfo'].get('authors', ['Unknown author']),
                "description": item['volumeInfo'].get('description', 'No description available'),
                "link": item['volumeInfo'].get('infoLink', '#')
            }
            recommendations.append(book)
    else:
        return "No recommendations found."

    return recommendations


def display_recommendations(recommendations):
    if isinstance(recommendations, str):
        print(recommendations)
        return

    for book in recommendations:
        print(f"Title: {book['title']}")
        print(f"Authors: {', '.join(book['authors'])}")
        print(f"Description: {book['description'][:200]}...")  
        print(f"Link: {book['link']}\n")






def curate_reads_bot():
    print("Welcome to CurateReads, your personalized book recommendation bot!")

    while True:
        query = input("What kind of books are you looking for? (e.g., 'mystery by Agatha Christie' or just 'Agatha Christie') ")
        author = extract_author(query)  

        if author:
            
            print(f"Fetching all books by {author}...")
            recommendations = recommend_books(f"author:{author}")  
            display_recommendations(recommendations)
        else:
            start_index = 0  
            more = True  

            while more:
                
                recommendations = recommend_books(query, start_index=start_index)
                display_recommendations(recommendations)

               
                user_input = input("Do you want more recommendations? (yes/no): ").strip().lower()

                if user_input == "yes":
                    start_index += 5  
                else:
                    more = False  

    
        new_search = input("Do you want to search for another type of book? (yes/no): ").strip().lower()
        if new_search != "yes":
            print("Thank you for using CurateReads! Goodbye!")
            break 

if __name__ == "__main__":
    curate_reads_bot()
